export const createUploadItem = (file, index) => ({
  id: `${Date.now()}-${index}-${file.name}`,
  file,
  sourceType: 'file',
  sourceUrl: null,
  name: file.name,
  progress: 0,
  stage: 'queued',
  stageLabel: null,
  status: 'pending',
  error: '',
  lyricsStatus: null,
  lyricsFormat: null,
  lyricsMessage: '',
  metadata: null,
  storageKey: null,
  postAction: null,
});

export const createYoutubeUploadItem = (url, index, hintTitle = '') => ({
  id: `${Date.now()}-${index}-yt`,
  file: null,
  sourceType: 'youtube',
  sourceUrl: url,
  hintTitle,
  name: url,
  progress: 0,
  stage: 'queued',
  stageLabel: null,
  status: 'pending',
  error: '',
  lyricsStatus: null,
  lyricsFormat: null,
  lyricsMessage: '',
  metadata: null,
  storageKey: null,
  postAction: null,
});